use_frameworks!
platform :ios, '11.0'

target 'CodableNetworking_Example' do
  pod 'CodableNetworking', :path => '../'

  target 'CodableNetworking_Tests' do
    inherit! :search_paths

    
  end
end
